### ISSUE TITLE
Make it possible to deploy DAOs from the production build

### ISSUE THREAD

**Issue by sogasg** [dOrgTech/dOrg#34]
> Out of the box, Arc.js contains the addresses of all of the Arc contracts as they have been migrated to Kovan...
https://daostack.github.io/arc.js/

**When running the dApp locally, it is possible to deploy a DAO to the Kovan testnet.
Once the dApp is built for production (`npm run app-build`) it does not work.**

I am getting an error: `Failed to create DAO. Error: Invalid number of arguments to Solidity function`.

```
"Error while deploying DAO:
index.ts:58 Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (errors.js:25)
    at p.validateArgs (function.js:78)
    at p.toPayload (function.js:97)
    at p.estimateGas (function.js:198)
    at contract.js:125
    at new Promise (<anonymous>)
    at contract.js:115"
```

**This needs investigation.**

Handy info
- https://github.com/daostack/arc.js/blob/e9c158e5d43d559f52fd773005c018270b490ac5/docs/Configuration.md
-https://daostack.github.io/arc.js/Configuration/#network-configuration
- https://daostack.github.io/arc.js/

**Comment by sogasg** [comment]
Perhaps the problem is that we do not log in the user: https://metamask.github.io/metamask-docs/Main_Concepts/Getting_Started#logging-in

**Comment by sogasg** [comment]
The "estimateGas" function called in daoCreator/forgeOrg fails.

If we manually comment out the "const totalGas = ..." line and remove all uses of the variable (just do not set the gas manually) it works.

See the temporary "fix" here: https://github.com/dOrgTech/arc.js/commit/04a9c56becfbd69b996e2721d3e865c883072a07

**Comment by sogasg** [comment]
If we do not find a solution for this in a reasonable time, we always have the option just to make the changes proposed above ourselves in our local copy of the Arc.js package and deploy it manually to GitHub Pages. I already have this working.

Then we also would have to turn off the automatic deployment in the Travis script.

This would not be a "real solution", but a workaround until we find a real solution.

**Comment by cd10012** [comment]
@sogasg Nice workaround, we may want to go this route in the interim if we wanted to make the proposal to submit the work as completed.

**Comment by cd10012** [comment]
@sogasg Thank you for picking this up!

**Comment by sogasg** [comment]
No longer relevant as we have removed the dependency on Arc.js #61
